# Generated by Django 4.2.6 on 2023-10-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='place',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
