# Generated by Django 4.2.6 on 2023-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_react_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
