# Generated by Django 4.2.6 on 2023-10-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_react_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
